### ISSUE TITLE
need shortcut for running copy css style/ copy react style

### ISSUE THREAD

**Issue by qalqi** [jiangyijie27/figma-copy-css-and-react-style#1]
we need a keyboard shortcut for running copy CSS style/ copy react style #1

**Comment by jiangyijie27** [comment]
First of all, it only can be used in Figma.app.

Figma does not support shortcuts for plugins yet.
I'm using macOS, so I can set a keyboard shortcut in Preferences->Keyboard->Shortcuts

1. Plugins->Development->Copy CSS + React Style->Copy CSS Style
2. Plugins->Development->Copy CSS + React Style->Copy React Style

![image](https://user-images.githubusercontent.com/7429808/89166907-4dd3b500-d5ad-11ea-982d-92c685fbe237.png)

(Sorry I'm using Chinese, but I think you can get it)
