### ISSUE TITLE
Can't paste the css or react copied style

### ISSUE THREAD

**Issue by mayconbelfort** [jiangyijie27/figma-copy-css-and-react-style#2]
Hi,

Sorry for the stupid question, but how I paste this code? 
When I do the paste in the editor nothing happens.

Thank you.

**Comment by jiangyijie27** [comment]
Hi @mayconbelfort , this plugin only works in Figma desktop app.
Do you use it in Chrome or any other web browser ?

**Comment by mayconbelfort** [comment]
Hi @jiangyijie27 
Yes, in Chrome. I'll try download the desktop app.

Thanks
